language: node_js
node_js:
  - 12 # Uses Node.js v12
services:
  - postgresql # Starts up PostgreSQL
addons:
  postgresql: '10' # Recent PostgreSQL version on Travis
dist: xenial # Uses Xenial environment
notifications:
  email:
    on_success: change # Default: change (only when going from broken to fixed)
    on_failure: always # Default: always (which is annoying, as it should be)
install:
  - npm ci # Faster, goes only from package-lock.json
before_script:
  - psql -c 'create database "elevate-test";' -U postgres # Remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # Test the code
  - npm run build # Make the bundle
# before_deploy:
#   - rm -rf node_modules # Omit from the tarball, since we skip cleanup
# deploy:
#   skip_cleanup: true # Prevents Travis from deleting the build
#   provider: heroku
#   app: YOUR-HEROKU-APP-NAME-HERE # See README
#   api_key:
#     secure: YOUR-***ENCRYPTED***-API-KEY-HERE # See README
